In [6]:
# Anotações e práticas de Métricas de Classificação

## Importações
import numpy as np
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

In [7]:
## Rótulos binários reais (Ex.: Sobreviveu = 1, Morreu = 0)
### '_true' é aplicado à valores REAIS
y_true = np.array([1,0,1,1,0,1,0,0,1,0])

## Previsões do modelo (Ex.: Previsões de sobrevivência)
### '_pred' é aplicado à valores PREVISTOS
y_pred = np.array([1,1,1,0,0,1,0,1,1,0])

# Matriz de Confusão:

## Verdadeiro Negativo, Falso Positivo, Falso Negativo e Verdadeiro Positivo
## [[VN, FP]
## [FN, VP]]

matriz = confusion_matrix(y_true, y_pred)
print("Matriz de Confusão: ")
print(matriz)
## Neste exemplo, VN=3, FP=2, FN=1, VP=4

# Acurácia:
acuracia = accuracy_score(y_true, y_pred)
print(f"\nAcurácia: {acuracia:.2f}")

# Precisão:
precisao = precision_score(y_true, y_pred)
print(f"Precisão: {precisao:.2f}")

# Revocação | Foco: Evitar FNs (Falsos Negativos)
revoacao = recall_score(y_true, y_pred)
print(f"Revocação: {revoacao:.2f}")

# F1-Score (equilíbrio)
## Equilíbrio entre os reais e previstos
f1 = f1_score(y_true, y_pred)
print(f"F1-Score: {f1:.2f}")

#-----------------------------------------------

# Resultado:

## Matriz de Confusão:

##  [[3 2]
##  [1 4]]

## Acurácia: 0.70
## Precisão: 0.67
## Revocação: 0.80
## F1-Score: 0.73

Matriz de Confusão: 
[[3 2]
 [1 4]]

Acurácia: 0.70
Precisão: 0.67
Revocação: 0.80
F1-Score: 0.73


In [8]:
# Separando dados de teste, modelos
## Outras importações já se encontram acima, mas para não nos perdermos no modelo, deixarei aqui também

import numpy as np
from sklearn.datasets import make_moons
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

In [11]:
# Gerando dataset artificial (2 luas com ruído)
X, y = make_moons(n_samples=500, noise=0.3, random_state=42)

# Separando em treino e teste
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42) ## 'test_size' é a porcentagem

# Árvore de Decisão sem utilizar limiar de profundidade (overfitting)
arvore = DecisionTreeClassifier(random_state=42)
arvore.fit(X_train, y_train)
y_pred_arvore = arvore.predict(X_test)

# Random Forest
floresta = RandomForestClassifier(random_state=42)
floresta.fit(X_train, y_train)
y_pred_floresta = floresta.predict(X_test)

# Métricas & Acurácia

print("--------Resultado da Acurácia--------")
print("Decision Tree - Treino: ", accuracy_score(y_test, y_pred_arvore))
print("Decision Tree - Teste: ", accuracy_score(y_test, y_pred_arvore))
print("Random Forest - Treino: ", accuracy_score(y_train, floresta.predict(X_train)))
print("Random Forest - Teste: ", accuracy_score(y_test, y_pred_floresta))

print("\n------ Decision Tree -------")
print("Matriz de Confusão:\n", confusion_matrix(y_test, y_pred_arvore))
print(f"Precisão: {precision_score(y_test, y_pred_arvore):.4f}")
print(f"Revocação: {recall_score(y_test, y_pred_arvore):.4f}")
print(f"F1-Score: {f1_score(y_test, y_pred_arvore):.4f}")

print("\n------ Random Forest -------")
print("Matriz de Confusão:\n", confusion_matrix(y_test, y_pred_floresta))
print(f"Precisão: {precision_score(y_test, y_pred_floresta):.4f}")
print(f"Revocação: {recall_score(y_test, y_pred_floresta):.4f}")
print(f"F1-Score: {f1_score(y_test, y_pred_floresta):.4f}")

# -----------------------------------------------------------------------

# Resultado da Acurácia

## Decision Tree - Treino:  0.8533333333333334
## Decision Tree - Teste:  0.8533333333333334
## Random Forest - Treino:  1.0
## Random Forest - Teste:  0.9066666666666666

# Decision Tree

## Matriz de Confusão:
##  [[68  7]
##  [15 60]]
## Precisão: 0.8955
## Revocação: 0.8000 (80% dos reais)
## F1-Score: 0.8451 (84%)

# Random Forest

## Matriz de Confusão:
##  [[71  4]
##  [10 65]]
## Precisão: 0.9420
## Revocação: 0.8667 (86% dos reais)
## F1-Score: 0.9028 (90%)

## F1-Score procura manter o equilíbrio, mas ainda há maior desempenho em Random Forest

--------Resultado da Acurácia--------
Decision Tree - Treino:  0.8533333333333334
Decision Tree - Teste:  0.8533333333333334
Random Forest - Treino:  1.0
Random Forest - Teste:  0.9066666666666666

------ Decision Tree -------
Matriz de Confusão:
 [[68  7]
 [15 60]]
Precisão: 0.8955
Revocação: 0.8000
F1-Score: 0.8451

------ Random Forest -------
Matriz de Confusão:
 [[71  4]
 [10 65]]
Precisão: 0.9420
Revocação: 0.8667
F1-Score: 0.9028
